# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:22
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('case', '0003_auto_20160212_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPUser',
            fields=[
            ],
            options={
                'verbose_name': 'MyPleasure User',
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='case.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='hash',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='case.Tag'),
        ),
    ]
